In [5]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
model = linear_model.LinearRegression()
model.fit(df[["area"]],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [11]:
import pickle

In [12]:
with open("model_pickle","wb") as f:
    pickle.dump(model,f)

In [13]:
with open("model_pickle","rb") as f:
    mp = pickle.load(f)

In [14]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [15]:
import joblib as jb

In [16]:
jb.dump(model,"model_joblib")

['model_joblib']

In [17]:
mj = jb.load("model_joblib")

In [18]:
mj.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [19]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432