In [1]:
import numpy as np
import time
import sys

l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)


28000
4000


In [3]:
SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took:",(time.time()-start)*1000)
#numpy array
start = time.time()
result = a1 + a2
print("Numpy took:",(time.time()-start)*1000)

Python list took: 0.9949207305908203
Numpy took: 0.0


In [6]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1/a2)
print(a1*a2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [11]:
a = np.array([5,6,7])
print(a[0])
print(a[1])
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)
print(a.dtype)
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a.itemsize)
print(a)


5
6
2
int32
8
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [12]:
a.size

6

In [14]:
a.shape

(3, 2)

In [16]:
a = np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
l = range(5)
l
l[0]
l[1]
np.arange(1,5)


array([1, 2, 3, 4])

In [22]:
np.arange(1,5,2)

array([1, 3])

In [25]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [26]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.shape

(3, 2)

In [28]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a.min()

1

In [35]:
a.max()

6

In [36]:
a.sum()

21

In [37]:
a.sum(axis=0)

array([ 9, 12])

In [38]:
a.sum(axis=1)

array([ 3,  7, 11])

In [39]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [40]:
np.std(a)

1.707825127659933

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [43]:
a

array([[1, 2],
       [3, 4]])

In [44]:
b

array([[5, 6],
       [7, 8]])

In [45]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
a-b

array([[-4, -4],
       [-4, -4]])

In [47]:
a*b

array([[ 5, 12],
       [21, 32]])

In [48]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [49]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [2]:
n = [6,7,8]

In [3]:
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [5]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [6]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [7]:
a[1,2]

3

In [8]:
a[0:2,2]

array([8, 3])

In [9]:
a[-1]

array([9, 3, 2])

In [10]:
a[-1,0:2]

array([9, 3])

In [11]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [12]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [13]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [14]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [15]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [17]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [22]:
a = np.arange(30).reshape(2,15)

In [23]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [25]:
result = np.hsplit(a,3)


In [26]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [28]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [29]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [30]:
result = np.vsplit(a,2)

In [31]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [32]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [33]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
b = a>4

In [36]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [38]:
a[b]=-1

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [41]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
for cell in a.flatten():
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [50]:
for x in np.nditer(a,order="F",flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [52]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...]=x*x

In [53]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [55]:
b = np.arange(3,15,4).reshape(3,1)

In [56]:
b

array([[ 3],
       [ 7],
       [11]])

In [59]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
