In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [16]:
iris = load_iris()

In [19]:
l_scores = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)
l_scores

array([0.96, 0.96, 0.94])

In [20]:
np.average(l_scores)

0.9533333333333333

In [21]:
d_scores = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
d_scores

array([0.98, 0.94, 0.98])

In [22]:
np.average(d_scores)

0.9666666666666667

In [27]:
s_scores = cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)
s_scores

array([0.98, 0.98, 0.96])

In [28]:
np.average(s_scores)

0.9733333333333333

In [31]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)
r_scores

array([0.98, 0.92, 0.96])

In [32]:
np.average(r_scores)

0.9533333333333333